# Generated by Django 2.1.7 on 2019-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('showtype', models.CharField(max_length=10)),
                ('eps', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
