# Generated by Django 2.1.7 on 2019-03-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='eps',
            new_name='episodes',
        ),
        migrations.AddField(
            model_name='show',
            name='weebtitle',
            field=models.CharField(default='WeebTitle', max_length=100),
        ),
    ]
