# Generated by Django 2.1.7 on 2019-03-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_auto_20190312_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='showtype',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
