# Generated by Django 2.1.7 on 2019-03-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_show_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='mal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='showtype',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
