# Generated by Django 2.1.7 on 2019-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_auto_20190312_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
