# Generated by Django 2.1.7 on 2019-03-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_auto_20190312_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='id',
        ),
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='mal_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
